//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trueques.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_B
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto_B()
        {
            this.Trueques = new HashSet<Trueque>();
        }
    
        public int idProductoB { get; set; }
        public string nombreProductoB { get; set; }
        public string imgProductoB { get; set; }
        public Nullable<int> idUsuarioB { get; set; }
        public Nullable<int> idEtiquetaB { get; set; }
        public Nullable<int> idProductoT { get; set; }
        public Nullable<bool> Disponible { get; set; }
    
        public virtual Etiqueta Etiqueta { get; set; }
        public virtual Producto_T Producto_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trueque> Trueques { get; set; }
    }
}
