//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trueques.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto_T()
        {
            this.Producto_B = new HashSet<Producto_B>();
            this.Trueques = new HashSet<Trueque>();
        }
    
        public int idProductoT { get; set; }
        public string nombreProductoT { get; set; }
        public byte[] imgProductoT { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idEtiqueta { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Etiqueta Etiqueta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_B> Producto_B { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trueque> Trueques { get; set; }
    }
}
