//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trueques.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trueque
    {
        public int idTrueque { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> idProductoT { get; set; }
        public Nullable<int> idProductoB { get; set; }
        public Nullable<int> idUsuarioT { get; set; }
        public Nullable<int> idUsuarioB { get; set; }
    
        public virtual Producto_B Producto_B { get; set; }
        public virtual Producto_T Producto_T { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
